name: Docker Image CI
      
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       echo ${{ secrets.DOCKER_SECRET }} | docker login -u nrrrus --password-stdin /
       ls -la /
       docker build -t my-nginx-image . /
       docker tag my-nginx-image nrrrus/nginx-test:latest /
       docker push nrrrus/nginx-test:latest /
       docker rmi -f my-nginx-image:latest /
       docker rmi -f nrrrus/nginx-test:latest
